name: Publish docker image
on:
  push:
    tags:
    - 'v*'

jobs:
  build-and-push:
    env:
      DOCKER_REPOSITORY: abnerfs/bot-musica-poc

    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v3

      - name: Get tag version
        run: | 
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.VERSION }}
